/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  podcastSidebar: [
    {
      type: 'category',
      label: '节目列表',
      collapsible: true,
      collapsed: false,
      link: {
        type: 'generated-index',
        title: '节目',
        description: ' ',
        keywords: ['guides'],
        slug: '/podcast',
        image: '/img/docusaurus.png',
      },
      items: [
        {
          type: 'autogenerated',
          dirName: 'podcast',
        },
      ],
    },
    {
      type: 'category',
      label: '系列列表',
      collapsible: true,
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'album',
        },
      ],
    },
    // {
    //   type: 'category',
    //   label: '单集列表',
    //   collapsible: true,
    //   collapsed: false,
    //   items: [
    //     {
    //       type: 'autogenerated',
    //       dirName: 'episode',
    //     },
    //   ],
    // },
  ],
};

module.exports = sidebars;
